# ==============================================================================
# Target Trial Emulation: Multiple Imputation (R Script)
#
# Description:
#   Loads the cohort data generated by the Python builder, performs 
#   Multiple Imputation by Chained Equations (MICE), and saves 5 imputed datasets.
#
# Dependencies:
#   install.packages(c("arrow", "tidyverse", "mice"))
# ==============================================================================

library(arrow)
library(tidyverse)
library(mice)

# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================

# File Paths
# NOTE: Points to the output from your 'build_target_trial.py' script
DATA_PATHS <- list(
  # Example: specific month or combined file from the builder output
  input_cohort = "./target_trial_data/trial_BB_HFrEF_2010_60/all.parquet",
  output_dir = "./imputed_data/"
)

# Study Parameters
PARAMS <- list(
  m_imputations = 5,
  seed = 1234
)

# Covariate Definitions
COVARIATES_CONFIG <- list(
  # Identifiers (Excluded from imputation model but kept in dataset)
  core = c("patid", "trial_start"),
  
  # Dates (Excluded from imputation model)
  dates = c("dod", "enddate", "end_followup_date_2y"),
  
  # Categorical Variables (To be converted to factors for MICE)
  # Updated: Using 'gen_ethnicity_mapped' instead of numeric version
  categorical = c(
    "gender",
    "gen_ethnicity_mapped", 
    "region", 
    "imd2015_5",
    "smoke"
  ),
  
  # Continuous Measurements (Targets for PMM imputation)
  numeric = c(
    "bmi", 
    "sbp",          
    "dbp",          
    "creatinine", 
    "tchdl_rat"     
  ),
  
  # Binary History Flags (Predictors)
  history_flags = c(
    "hypertension_history", "diabetes_history", "ischaemic_heart_disease_history",
    "atrial_fibrillation_history", "stroke_history", "dyslipidaemia_history",
    "asthma_history", "peripheral_arterial_disease_history",
    "valve_disorders_history", "chronic_kidney_disease_history",
    "pulmonary_embolism_history", "malignant_cancer_history"
  ),
  
  # Co-medications (Predictors)
  meds = c(
    "ACE", "ARB", "Diuretics", "CCB", "statin", 
    "digoxin", "anticoagulant", "antiplatelet"
  )
)

# Treatment and Outcome (Must be included)
VAR_EXTRAS <- c("treatment", "all_cause_mortality_2y") # Matches builder output columns

# ==============================================================================
# 2. DATA LOADING & PREPROCESSING
# ==============================================================================

load_and_preprocess <- function(file_path, config) {
  
  # 1. Define all columns to load
  cols_to_keep <- unique(c(
    config$core, config$dates, config$categorical, 
    config$numeric, config$history_flags, config$meds, VAR_EXTRAS
  ))
  
  message(sprintf("Loading columns from %s...", file_path))
  
  # 2. Read Parquet
  df <- read_parquet(file_path, col_select = all_of(cols_to_keep))
  
  # 3. Data Type Conversion for MICE
  
  # Convert categoricals (strings) to Factors (required for polyreg)
  for (col in config$categorical) {
    if (col %in% names(df)) {
      df[[col]] <- as.factor(df[[col]])
    }
  }
  
  # Convert binary flags (0/1 integers) to Factors (required for logreg)
  binary_vars <- c(config$history_flags, config$meds, "all_cause_mortality_2y", "treatment")
  for (col in binary_vars) {
    if (col %in% names(df)) {
      df[[col]] <- as.factor(df[[col]])
    }
  }
  
  # Ensure numeric columns are numeric
  for (col in config$numeric) {
    if (col %in% names(df)) {
      df[[col]] <- as.numeric(df[[col]])
    }
  }
  
  return(df)
}

# ==============================================================================
# 3. IMPUTATION EXECUTION
# ==============================================================================

run_imputation <- function(df, config, m = 5, seed = 1234) {
  
  # 1. Setup Prediction Matrix
  # Exclude IDs and Dates from the predictor set
  exclude_cols <- c(config$core, config$dates)
  
  # Check for missingness
  missing_stats <- colSums(is.na(df))
  print("Columns with missing values:")
  print(missing_stats[missing_stats > 0])
  
  # 2. Initialize MICE (dry run)
  ini <- mice(df, maxit = 0, print = FALSE)
  pred <- ini$predictorMatrix
  meth <- ini$method
  
  # 3. Configure Predictor Matrix
  # 0 = do not use as predictor
  pred[, intersect(colnames(pred), exclude_cols)] <- 0
  
  # 4. Configure Methods
  # Do not impute the excluded columns
  meth[intersect(names(meth), exclude_cols)] <- ""
  
  # Use PMM (Predictive Mean Matching) for continuous variables
  # This preserves the distribution and prevents impossible values (e.g. negative BMI)
  meth[config$numeric] <- "pmm"
  
  # MICE automatically selects 'polyreg' for >2 level factors (Ethnicity)
  # and 'logreg' for 2 level factors (Binary flags), but we can verify:
  # meth["gen_ethnicity_mapped"] should default to polyreg if it has >2 levels
  
  message("Starting MICE imputation (PMM for numerics)...")
  
  # 5. Run MICE
  imp <- mice(
    df,
    m = m,
    method = meth,
    predictorMatrix = pred,
    seed = seed,
    printFlag = TRUE
  )
  
  return(imp)
}

# ==============================================================================
# 4. SAVING OUTPUTS
# ==============================================================================

save_imputed_datasets <- function(imp_object, output_dir) {
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  m <- imp_object$m
  
  for (i in 1:m) {
    # Extract complete dataset i
    completed_data <- complete(imp_object, i)
    
    # Save as parquet
    file_name <- file.path(output_dir, sprintf("imputed_dataset_%d.parquet", i))
    write_parquet(completed_data, file_name)
    message(sprintf("Saved: %s", file_name))
  }
}

# ==============================================================================
# 5. MAIN
# ==============================================================================

main <- function() {
  # Load Data
  if (!file.exists(DATA_PATHS$input_cohort)) {
    stop(sprintf("Input file not found: %s", DATA_PATHS$input_cohort))
  }
  
  df <- load_and_preprocess(DATA_PATHS$input_cohort, COVARIATES_CONFIG)
  
  # Run Imputation
  imputed_object <- run_imputation(df, COVARIATES_CONFIG, m = PARAMS$m_imputations, seed = PARAMS$seed)
  
  # Save Results
  save_imputed_datasets(imputed_object, DATA_PATHS$output_dir)
  
  message("Imputation pipeline completed successfully.")
}

# Execute
main()